{
 "title": "BNG statistics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NAT Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_nat_sessions_state_isa_nat_group_member_resources_ports_value{member_id=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscribers Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_subs_stats_state_subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"subscribers-total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PPP Sessios",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_subs_stats_state_subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"ppp-sessions-local-pppoe\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Hosts IPv4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_subs_stats_state_subscriber_mgmt_statistics_total_hosts_current_value{total_hosts_counter=\"ipv4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Hosts IPv6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_subs_stats_state_subscriber_mgmt_statistics_total_hosts_current_value{total_hosts_counter=\"ipv6\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_cpu_stats_state_system_cpu_summary_usage_cpu_usage{cpu_sample_period=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port 1/1/2 traffic (To ISP)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(gnmic_port_stats_state_port_statistics_in_octets{port_port_id=\"1/1/2\"}[$__rate_interval])*8",
     "legendFormat": "Port {{port_port_id}} In traffic"
    },
    {
     "expr": "rate(gnmic_port_stats_state_port_statistics_out_octets{port_port_id=\"1/1/2\"}[$__rate_interval])*8",
     "legendFormat": "Port {{port_port_id}} Out traffic"
    }
   ]
  },
  {
   "title": "Port 1/1/3 traffic (To OLT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(gnmic_port_stats_state_port_statistics_in_octets{port_port_id=\"1/1/3\"}[$__rate_interval])*8",
     "legendFormat": "Port {{port_port_id}} In traffic"
    },
    {
     "expr": "rate(gnmic_port_stats_state_port_statistics_out_octets{port_port_id=\"1/1/3\"}[$__rate_interval])*8",
     "legendFormat": "Port {{port_port_id}} Out traffic"
    }
   ]
  },
  {
   "title": "Logs Volume",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (loglevel)(count_over_time({job=\"syslog\"} [$__interval]))",
     "legendFormat": "logs"
    }
   ]
  },
  {
   "title": "BNG Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"syslog\"} |= ``"
    }
   ]
  }
 ]
}